destination: "build"
source: "source"
timezone: "America/Chicago"
highlighter: none
kramdown:
  auto_ids: false
  smart_quotes: ["apos", "apos", "quot", "quot"]

plugins:
  - "jekyll-compose"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:day/:title:output_ext"
