destination: "build"
source: "source"

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: "/posts/:year/:month/:day/:title:output_ext"
