source 'https://rubygems.org'

gem 'builder'
gem 'dotenv'
gem 'middleman'
gem 'middleman-blog'
gem 'middleman-google-analytics'
gem 'redcarpet'
gem 'html-proofer'
gem 'rake'
gem 'danger'
gem 'danger-commit_lint'
