version: 2
jobs:
  test:
    working_directory: ~/jonallured.com
    docker:
      - image: cimg/ruby:3.4.5-node
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_PATH: "vendor/bundle"
      BUNDLE_RETRY: "3"
    steps:
      - run:
          name: Install Imagemagick
          command: sudo apt-get update && sudo apt-get install -y libmagickcore-dev
      - checkout
      - restore_cache:
          name: Restore bundler cache
          key: bundler-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install
      - save_cache:
          name: Save bundler cache
          key: bundler-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake
workflows:
  version: 2
  default:
    jobs:
      - test
