version: 2

jobs:
  test:
    working_directory: ~/jonallured.com
    docker:
      - image: cimg/ruby:3.0.1-node
    steps:
      - checkout
      - restore_cache:
          name: Restore bundler cache
          key: bundler-v2-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle install
          command: bundle install --jobs=4 --retry=3 --path vendor/bundle
      - save_cache:
          name: Save bundler cache
          key: bundler-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: Run tests
          command: bundle exec rake

workflows:
  version: 2
  default:
    jobs:
      - test
