name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install ImageMagick
        run: sudo apt-get update && sudo apt-get install -y imagemagick libmagickwand-dev
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Run the default task
        run: bundle exec rake
